OPENCM3_DIR = ../../../lib/libopencm3
BINARY = regex
DEVICE = stm32f051r8t6
OBJS += ../../../lib/microrl/src/microrl.o
OBJS += ../../../lib/tiny-regex-c/re.o
CFLAGS += -I../../../lib/microrl/src/
CFLAGS += -I../../../lib/tiny-regex-c/
include ../../../fw/stm32/f0/libopencm3.target.mk 
