OPENCM3_DIR = ../../../lib/libopencm3
BINARY = rl
DEVICE = stm32f051r8t6
OBJS += ../../../lib/microrl/src/microrl.o
CFLAGS += -I../../../lib/microrl/src/
include ../../../fw/stm32/f0/libopencm3.target.mk 
